table _Measures
	lineageTag: c76a8035-7f37-463e-981d-4392f6006fb8

	measure Sales = COUNTROWS(Sales)
		formatString: 0
		lineageTag: fa359826-c78d-4e88-a1c2-35e85a3cf21e

	measure TotalAmount = SUMX(Sales,Sales[Quantity]*Sales[Unit Price])
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 2ba86128-242d-4b82-bf7d-1afb8b747a34

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	partition _Measures = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", Int64.Type}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	changedProperty = Name

	annotation PBI_ResultType = Table

